# Generated by Django 3.0.8 on 2020-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userSup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=100)),
                ('phoneNumber', models.PositiveSmallIntegerField()),
                ('profilePhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
