# Generated by Django 3.0.8 on 2020-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QANeiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersup',
            name='phoneNumber',
            field=models.IntegerField(max_length=15),
        ),
    ]
